[package]
name = "fm-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
futuresdr = { path = "../..", features=["soapy", "audio"] }
num-complex = "0.4.0"
rand = "0.8.4"
clap = { version="3.0.13", features=["derive"] }
